on: 
  workflow_dispatch: 
  
name: exemplo-actions

jobs:
  run-code:
    runs-on: ubuntu-latest
    steps:
      - uses: r-lib/actions/setup-r@v2
      - name: escrever-mensagem-no-terminal
        run: echo "Olá GitHub Actions!"
      - name: escrever-mensagem-com-R
        run: Rscript -e 'print("Olá GitHub Actions, agora usando R!")'